# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# See: https://circleci.com/docs/configuration-reference/#executors
executors:
  ruby-executor:
    docker:
      - image: ruby:3.2.2
        environment:
          RAILS_ENV: test

      - image: cimg/postgres:16.0
        environment:
          POSTGRES_USER: budgetizer
          POSTGRES_DB: budgetizer_test
  node-executor:
    docker:
      - image: node:18.16.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  api-quality:
    working_directory: ~/budgetizer/api
    executor: ruby-executor
    steps:
      - checkout:
          path: ~/budgetizer
      - run:
          name: Install Dependencies
          command: bundle install
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - run:
          name: Rubycritic
          command: bundle exec rubycritic --no-browser --format lint
  api-test:
    working_directory: ~/budgetizer/api
    executor: ruby-executor
    steps:
      - checkout:
          path: ~/budgetizer
      - run:
          name: Install Dependencies
          command: bundle install
      - run:
          name: Setup DB
          command: rails db:create db:migrate
      - run:
          name: RSpec
          command: bundle exec rspec

  web-quality:
    working_directory: ~/budgetizer/web
    executor: node-executor
    steps:
      - checkout:
          path: ~/budgetizer
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: ESLint
          command: yarn lint
  web-build:
    working_directory: ~/budgetizer/web
    executor: node-executor
    steps:
      - checkout:
          path: ~/budgetizer
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
  web-test:
    working_directory: ~/budgetizer/web
    executor: node-executor
    steps:
      - checkout:
          path: ~/budgetizer
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Vitest
          command: yarn test

workflows:
  api:
    jobs:
      - api-quality
      - api-test:
          requires:
            - api-quality
  web:
    jobs:
      - web-quality
      - web-test
      - web-build:
          requires:
            - web-quality
            - web-test
