# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# See: https://circleci.com/docs/configuration-reference/#executors
executors:
  node-executor:
    docker:
      - image: node:18.16.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  quality:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: ESLint
          command: yarn lint
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Vitest
          command: yarn test

workflows:
  quality_and_test:
    jobs:
      - quality
      - test
      - build:
          requires:
            - quality
            - test
