require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  CountRepeatedAttributes: false